# Generated by Django 5.0.3 on 2024-03-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_reservation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='size',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('lek', 'lek')], default='eur', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
